/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CJBaoKlBIle
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

export function AudioTextChat({
  text,
}: {
  text: string;
}) {
  return (
    <div className="flex flex-col items-center justify-center w-full max-w-2xl mx-auto space-y-6">
      <div className="w-full rounded-lg overflow-hidden relative">
        <audio
          autoPlay
          controls
          className="w-full"
        >
          <source
            src="/sample-audio.mp3"
            type="audio/mpeg"
          />
          Your browser does not support the audio
          element.
        </audio>
      </div>
      <div className="w-full bg-gray-900 rounded-lg p-4 text-white">
        <div className="flex flex-col gap-2">
          <div className="text-sm font-medium">
            Synchronized Captions
          </div>
          <div className="text-sm text-gray-300">
            <p>{text}</p>
          </div>
        </div>
      </div>
    </div>
  );
}
